<?php

namespace AppBundle\Repository;

/**
 * IconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconRepository extends \Doctrine\ORM\EntityRepository
{

      /**
      * @param $icon
      * @return mixed
      */
      public function findByIcon($icon)
      {
         $qb = $this->createQueryBuilder('i');
         $qb->where('i.icon = :icon')
               ->setParameter('icon', $icon);
         return $qb->getQuery()->getResult();
      }

      public function findAllIcons()
      {
         $qb = $this->createQueryBuilder('i');
         return $qb->getQuery()->getResult();
      }

      public function deleteIcon($id)
      {
         $em = $this->getEntityManager();
         $icon = $em->getRepository(Icon::class)->find($id);
         $em->remove($icon);
         $em->flush();
      }

     
}
